#!/usr/bin/env python3
"""Convert one canonical LEONES result JSON document into Markdown.

One job only: presentation. It does not discover hardware, benchmark, publish,
or calculate aggregate statistics.

Usage:
    python3 scripts/leones-report.py result.json --output result.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def task_line(code: str, task: dict | None) -> str:
    if not task:
        return f"| {code} | not_run | — |"
    return f"| {code} | {task.get('status', 'not_run')} | {task.get('elapsed_seconds', '—')} |"


def render(data: dict) -> str:
    hw = data.get("hardware", {})
    model = data.get("model", {})
    inf = data.get("inference", {})
    lotb = data.get("lotb", {})
    software = data.get("software", {})
    lines = [
        "# LEONES experiment report", "",
        f"**Schema:** `{data.get('schema_version', 'unknown')}`  ",
        f"**Status:** `{data.get('status', 'reported')}`", "",
        "## Hardware", "",
        f"- Profile: `{hw.get('profile', 'unknown')}`",
        f"- CPU: {hw.get('cpu', 'unknown')}",
        f"- Architecture: {hw.get('architecture', 'unknown')}",
        f"- Cores / threads: {hw.get('cores', '—')} / {hw.get('threads', '—')}",
        f"- RAM: {hw.get('ram_gb', '—')} GB",
        f"- GPU: {hw.get('gpu', 'none reported')}",
        f"- VRAM: {hw.get('vram_gb', '—')} GB",
        f"- OS: {hw.get('os', 'unknown')}", "",
        "## Model", "",
        f"- Name: `{model.get('name', 'unknown')}`",
        f"- Format: `{model.get('format', '—')}`",
        f"- Quantisation: `{model.get('quantization', '—')}`",
        f"- Size: `{model.get('size_bytes', '—')}` bytes",
        f"- SHA-256: `{model.get('sha256', '—')}`", "",
        "## Inference", "",
        f"- Elapsed: {inf.get('elapsed_seconds', '—')} s",
        f"- Prompt tokens: {inf.get('prompt_tokens', '—')}",
        f"- Completion tokens: {inf.get('completion_tokens', '—')}",
        f"- Generation: {inf.get('generation_tokens_per_second', '—')} tok/s", "",
        "## LOTB", "", "| Task | Status | Time (s) |", "|---|---|---:|",
    ]
    for code in ("B01", "B02", "B03", "B04", "B05"):
        lines.append(task_line(code, lotb.get(code)))
    lines += ["", "## Software", ""]
    for key, value in software.items():
        lines.append(f"- {key}: `{value}`")
    lines += ["", "## Notes", "", data.get("notes", "No additional notes."), "",
              "---", "Generated by `scripts/leones-report.py`. Publication and verification are separate steps.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a LEONES Markdown report")
    parser.add_argument("result", help="Canonical LEONES result JSON")
    parser.add_argument("--output", required=True, help="Markdown output path")
    args = parser.parse_args()
    data = json.loads(Path(args.result).read_text(encoding="utf-8"))
    Path(args.output).write_text(render(data), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
