-- Open LLM Atlas — Recommendation Engine v0.1
-- Additive layer for LEONES. Does not replace models/families/organizations/taxonomy_barahona.
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS hardware_profiles (hardware_id TEXT PRIMARY KEY,name TEXT NOT NULL,cpu_vendor TEXT,cpu_model TEXT,gpu_vendor TEXT,gpu_model TEXT,gpu_count INTEGER DEFAULT 0,vram_gb REAL,ram_gb REAL NOT NULL,unified_memory INTEGER DEFAULT 0,memory_bandwidth_gbps REAL,os TEXT,architecture TEXT,notes TEXT,source_id TEXT,last_verified TEXT);
CREATE TABLE IF NOT EXISTS runtime_profiles (runtime_id TEXT PRIMARY KEY,name TEXT NOT NULL,version TEXT,backend TEXT,supported_architectures TEXT,supported_formats TEXT,supported_quantizations TEXT,supported_hardware TEXT,serving_modes TEXT,maturity TEXT,source_id TEXT,last_verified TEXT);
CREATE TABLE IF NOT EXISTS workload_profiles (workload_id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT,min_context_tokens INTEGER,typical_input_tokens INTEGER,typical_output_tokens INTEGER,concurrency INTEGER DEFAULT 1,latency_priority REAL DEFAULT 0.5,throughput_priority REAL DEFAULT 0.5,quality_priority REAL DEFAULT 0.5,memory_priority REAL DEFAULT 0.5,notes TEXT);
CREATE TABLE IF NOT EXISTS model_deployments (deployment_id TEXT PRIMARY KEY,model_id TEXT NOT NULL,quantization TEXT,format TEXT,runtime_id TEXT,hardware_id TEXT,context_tokens INTEGER,workload_id TEXT,estimated_memory_gb REAL,estimated_tps REAL,viability_status TEXT DEFAULT 'unknown',viability_reason TEXT,source_id TEXT,last_verified TEXT);
CREATE TABLE IF NOT EXISTS performance_observations (observation_id TEXT PRIMARY KEY,deployment_id TEXT,model_id TEXT NOT NULL,hardware_id TEXT,runtime_id TEXT,workload_id TEXT,quantization TEXT,format TEXT,prompt_tokens INTEGER,output_tokens INTEGER,context_tokens INTEGER,concurrency INTEGER DEFAULT 1,ttft_ms REAL,tpot_ms REAL,tokens_per_second REAL,requests_per_second REAL,memory_used_gb REAL,power_watts REAL,success INTEGER,failure_reason TEXT,source_id TEXT NOT NULL,source_url TEXT,measurement_date TEXT,methodology TEXT,confidence TEXT DEFAULT 'unknown',notes TEXT);
CREATE TABLE IF NOT EXISTS capability_observations (capability_observation_id TEXT PRIMARY KEY,model_id TEXT NOT NULL,capability TEXT NOT NULL,score REAL,score_max REAL DEFAULT 100,benchmark_name TEXT,benchmark_version TEXT,source_id TEXT NOT NULL,source_url TEXT,observation_date TEXT,confidence TEXT DEFAULT 'unknown',notes TEXT);
CREATE TABLE IF NOT EXISTS sources (source_id TEXT PRIMARY KEY,name TEXT NOT NULL,source_type TEXT NOT NULL,url TEXT,methodology TEXT,authority_level TEXT,retrieved_at TEXT,notes TEXT);
CREATE INDEX IF NOT EXISTS idx_perf_model ON performance_observations(model_id);
CREATE INDEX IF NOT EXISTS idx_perf_hardware ON performance_observations(hardware_id);
CREATE INDEX IF NOT EXISTS idx_perf_runtime ON performance_observations(runtime_id);
CREATE INDEX IF NOT EXISTS idx_deploy_model ON model_deployments(model_id);
CREATE INDEX IF NOT EXISTS idx_deploy_hardware ON model_deployments(hardware_id);
INSERT OR IGNORE INTO sources(source_id,name,source_type,url,methodology,authority_level,retrieved_at,notes) VALUES ('msa','Model Speed Arena','empirical_benchmark','https://msa.millaguie.net/#sc-local','Observed inference performance under source methodology','external_empirical','2026-08-15','MSA measurements are observations, not intrinsic model properties.');